# Generated by Django 3.1.7 on 2023-03-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import_to_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=256)),
                ('region', models.CharField(max_length=64)),
                ('street', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ImportInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=64)),
                ('insert_date', models.DateTimeField()),
                ('data_size', models.PositiveIntegerField()),
                ('file', models.FilePathField()),
            ],
        ),
    ]
